# Generated by Django 2.2.7 on 2020-12-02 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashiongebeya', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='brand',
            field=models.CharField(default='shoe', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='trending',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='what',
            field=models.CharField(choices=[('shoes', 'shoes'), ('shirt', 'shirt'), ('skirt', 'skirt'), ('trouser', 'trouser'), ('jeans', 'jeans'), ('other', 'other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='mycart',
            name='pending',
            field=models.BooleanField(default=True),
        ),
    ]
