# Generated by Django 2.2.7 on 2020-12-03 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fashiongebeya', '0002_auto_20201202_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='what',
            field=models.CharField(choices=[('shoes', 'shoes'), ('shirt', 'shirt'), ('skirt', 'skirt'), ('trouser', 'trouser'), ('jacket', 'jacket'), ('other', 'other')], default='other', max_length=20),
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fashiongebeya.Item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
